<<<<<<< HEAD
-- MySQL Script generated by MySQL Workbench
-- Mon Jan 30 21:58:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8mb3 ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`categories` (
  `idCategories` INT NOT NULL,
  `name_categories` VARCHAR(45) NOT NULL,
  `description_categories` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategories`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`clients` (
  `idClients` INT NOT NULL AUTO_INCREMENT,
  `name_clients` VARCHAR(45) NOT NULL,
  `last_name_clients` VARCHAR(45) NOT NULL,
  `age_clients` INT NOT NULL,
  `phone_clients` VARCHAR(15) NOT NULL,
  `email_clients` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idClients`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`delivery` (
  `idDelivery` INT NOT NULL,
  `id_tracker_delivery` VARCHAR(45) NOT NULL,
  `date_registered` DATE NULL,
  PRIMARY KEY (`idDelivery`),
  UNIQUE INDEX `id_tracker_delivery_UNIQUE` (`id_tracker_delivery` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`shippers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`shippers` (
  `idShippers` INT NOT NULL,
  `company_name_shippers` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idShippers`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`delivery_shippers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`delivery_shippers` (
  `idDelivery` INT NOT NULL,
  `idShippers` INT NOT NULL,
  `date_creation` DATE NOT NULL,
  PRIMARY KEY (`idDelivery`, `idShippers`),
  INDEX `fk_Delivery_has_Shippers_Shippers1_idx` (`idShippers` ASC) VISIBLE,
  INDEX `fk_Delivery_has_Shippers_Delivery1_idx` (`idDelivery` ASC) VISIBLE,
  CONSTRAINT `fk_Delivery_has_Shippers_Delivery1`
    FOREIGN KEY (`idDelivery`)
    REFERENCES `shop`.`delivery` (`idDelivery`),
  CONSTRAINT `fk_Delivery_has_Shippers_Shippers1`
    FOREIGN KEY (`idShippers`)
    REFERENCES `shop`.`shippers` (`idShippers`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`offices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`offices` (
  `idOffices` INT NOT NULL,
  `name_offices` VARCHAR(45) NOT NULL,
  `department` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOffices`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`employees` (
  `idEmployees` INT NOT NULL AUTO_INCREMENT,
  `name_employees` VARCHAR(45) NOT NULL,
  `last_name_employees` VARCHAR(45) NOT NULL,
  `age_employees` INT NOT NULL,
  `phone_employees` VARCHAR(15) NOT NULL,
  `email_employees` VARCHAR(50) NOT NULL,
  `salary_employees` DOUBLE NOT NULL,
  `idOffices` INT NOT NULL,
  PRIMARY KEY (`idEmployees`),
  INDEX `fk_Employees_Offices1_idx` (`idOffices` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Offices1`
    FOREIGN KEY (`idOffices`)
    REFERENCES `shop`.`offices` (`idOffices`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`orders` (
  `idOrders` INT NOT NULL,
  `amount_orders` DOUBLE NOT NULL,
  `date_orders` DATE NOT NULL,
  `idClients` INT NOT NULL,
  `idEmployees` INT NOT NULL,
  `idDelivery` INT NOT NULL,
  PRIMARY KEY (`idOrders`),
  INDEX `fk_Orders_Employees_idx` (`idEmployees` ASC) VISIBLE,
  INDEX `fk_Orders_Clients1_idx` (`idClients` ASC) VISIBLE,
  INDEX `fk_Orders_Delivery1_idx` (`idDelivery` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Clients1`
    FOREIGN KEY (`idClients`)
    REFERENCES `shop`.`clients` (`idClients`),
  CONSTRAINT `fk_Orders_Delivery1`
    FOREIGN KEY (`idDelivery`)
    REFERENCES `shop`.`delivery` (`idDelivery`),
  CONSTRAINT `fk_Orders_Employees`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `shop`.`employees` (`idEmployees`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`inventory` (
  `idInventory` INT NOT NULL,
  `stock_inventory` DOUBLE NOT NULL,
  `date_adquisition_inventory` DATE NOT NULL,
  PRIMARY KEY (`idInventory`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`suppliers` (
  `idSuppliers` INT NOT NULL,
  `company_name_suppliers` VARCHAR(45) NOT NULL,
  `email_suppliers` VARCHAR(45) NOT NULL,
  `phone_suppliers` VARCHAR(45) NOT NULL,
  `contact_suppliers` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSuppliers`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`products` (
  `idProducts` INT NOT NULL,
  `name_products` VARCHAR(45) NOT NULL,
  `quantity_products` INT NOT NULL,
  `price_sell_products` DOUBLE NOT NULL,
  `price_buy_products` DOUBLE NOT NULL,
  `idSuppliers` INT NOT NULL,
  `idCategories` INT NOT NULL,
  `idInventory` INT NOT NULL,
  PRIMARY KEY (`idProducts`),
  INDEX `fk_Products_Suppliers1_idx` (`idSuppliers` ASC) VISIBLE,
  INDEX `fk_Products_Categories1_idx` (`idCategories` ASC) VISIBLE,
  INDEX `fk_Products_Inventory1_idx` (`idInventory` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Categories1`
    FOREIGN KEY (`idCategories`)
    REFERENCES `shop`.`categories` (`idCategories`),
  CONSTRAINT `fk_Products_Inventory1`
    FOREIGN KEY (`idInventory`)
    REFERENCES `shop`.`inventory` (`idInventory`),
  CONSTRAINT `fk_Products_Suppliers1`
    FOREIGN KEY (`idSuppliers`)
    REFERENCES `shop`.`suppliers` (`idSuppliers`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`detail_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`detail_orders` (
  `idDetail_orders` INT NOT NULL,
  `idOrders` INT NOT NULL,
  `idProducts` INT NOT NULL,
  PRIMARY KEY (`idDetail_orders`),
  INDEX `fk_Detail_orders_Orders1_idx` (`idOrders` ASC) VISIBLE,
  INDEX `fk_Detail_orders_Products1_idx` (`idProducts` ASC) VISIBLE,
  CONSTRAINT `fk_Detail_orders_Orders1`
    FOREIGN KEY (`idOrders`)
    REFERENCES `shop`.`orders` (`idOrders`),
  CONSTRAINT `fk_Detail_orders_Products1`
    FOREIGN KEY (`idProducts`)
    REFERENCES `shop`.`products` (`idProducts`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`payments` (
  `id_payments` INT NOT NULL,
  `idOrders` INT NOT NULL,
  `amount_payments` VARCHAR(45) NOT NULL,
  `date_payments` DATE NOT NULL,
  PRIMARY KEY (`id_payments`),
  INDEX `fk_Payments_Orders1_idx` (`idOrders` ASC) VISIBLE,
  CONSTRAINT `fk_Payments_Orders1`
    FOREIGN KEY (`idOrders`)
    REFERENCES `shop`.`orders` (`idOrders`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
=======
-- MySQL Script generated by MySQL Workbench
-- Mon Jan 30 21:58:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8mb3 ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`categories` (
  `idCategories` INT NOT NULL,
  `name_categories` VARCHAR(45) NOT NULL,
  `description_categories` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategories`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`clients` (
  `idClients` INT NOT NULL AUTO_INCREMENT,
  `name_clients` VARCHAR(45) NOT NULL,
  `last_name_clients` VARCHAR(45) NOT NULL,
  `age_clients` INT NOT NULL,
  `phone_clients` VARCHAR(15) NOT NULL,
  `email_clients` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idClients`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`delivery` (
  `idDelivery` INT NOT NULL,
  `id_tracker_delivery` VARCHAR(45) NOT NULL,
  `date_registered` DATE NULL,
  PRIMARY KEY (`idDelivery`),
  UNIQUE INDEX `id_tracker_delivery_UNIQUE` (`id_tracker_delivery` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`shippers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`shippers` (
  `idShippers` INT NOT NULL,
  `company_name_shippers` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idShippers`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`delivery_shippers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`delivery_shippers` (
  `idDelivery` INT NOT NULL,
  `idShippers` INT NOT NULL,
  `date_creation` DATE NOT NULL,
  PRIMARY KEY (`idDelivery`, `idShippers`),
  INDEX `fk_Delivery_has_Shippers_Shippers1_idx` (`idShippers` ASC) VISIBLE,
  INDEX `fk_Delivery_has_Shippers_Delivery1_idx` (`idDelivery` ASC) VISIBLE,
  CONSTRAINT `fk_Delivery_has_Shippers_Delivery1`
    FOREIGN KEY (`idDelivery`)
    REFERENCES `shop`.`delivery` (`idDelivery`),
  CONSTRAINT `fk_Delivery_has_Shippers_Shippers1`
    FOREIGN KEY (`idShippers`)
    REFERENCES `shop`.`shippers` (`idShippers`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`offices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`offices` (
  `idOffices` INT NOT NULL,
  `name_offices` VARCHAR(45) NOT NULL,
  `department` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOffices`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`employees` (
  `idEmployees` INT NOT NULL AUTO_INCREMENT,
  `name_employees` VARCHAR(45) NOT NULL,
  `last_name_employees` VARCHAR(45) NOT NULL,
  `age_employees` INT NOT NULL,
  `phone_employees` VARCHAR(15) NOT NULL,
  `email_employees` VARCHAR(50) NOT NULL,
  `salary_employees` DOUBLE NOT NULL,
  `idOffices` INT NOT NULL,
  PRIMARY KEY (`idEmployees`),
  INDEX `fk_Employees_Offices1_idx` (`idOffices` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Offices1`
    FOREIGN KEY (`idOffices`)
    REFERENCES `shop`.`offices` (`idOffices`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`orders` (
  `idOrders` INT NOT NULL,
  `amount_orders` DOUBLE NOT NULL,
  `date_orders` DATE NOT NULL,
  `idClients` INT NOT NULL,
  `idEmployees` INT NOT NULL,
  `idDelivery` INT NOT NULL,
  PRIMARY KEY (`idOrders`),
  INDEX `fk_Orders_Employees_idx` (`idEmployees` ASC) VISIBLE,
  INDEX `fk_Orders_Clients1_idx` (`idClients` ASC) VISIBLE,
  INDEX `fk_Orders_Delivery1_idx` (`idDelivery` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Clients1`
    FOREIGN KEY (`idClients`)
    REFERENCES `shop`.`clients` (`idClients`),
  CONSTRAINT `fk_Orders_Delivery1`
    FOREIGN KEY (`idDelivery`)
    REFERENCES `shop`.`delivery` (`idDelivery`),
  CONSTRAINT `fk_Orders_Employees`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `shop`.`employees` (`idEmployees`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`inventory` (
  `idInventory` INT NOT NULL,
  `stock_inventory` DOUBLE NOT NULL,
  `date_adquisition_inventory` DATE NOT NULL,
  PRIMARY KEY (`idInventory`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`suppliers` (
  `idSuppliers` INT NOT NULL,
  `company_name_suppliers` VARCHAR(45) NOT NULL,
  `email_suppliers` VARCHAR(45) NOT NULL,
  `phone_suppliers` VARCHAR(45) NOT NULL,
  `contact_suppliers` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSuppliers`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`products` (
  `idProducts` INT NOT NULL,
  `name_products` VARCHAR(45) NOT NULL,
  `quantity_products` INT NOT NULL,
  `price_sell_products` DOUBLE NOT NULL,
  `price_buy_products` DOUBLE NOT NULL,
  `idSuppliers` INT NOT NULL,
  `idCategories` INT NOT NULL,
  `idInventory` INT NOT NULL,
  PRIMARY KEY (`idProducts`),
  INDEX `fk_Products_Suppliers1_idx` (`idSuppliers` ASC) VISIBLE,
  INDEX `fk_Products_Categories1_idx` (`idCategories` ASC) VISIBLE,
  INDEX `fk_Products_Inventory1_idx` (`idInventory` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Categories1`
    FOREIGN KEY (`idCategories`)
    REFERENCES `shop`.`categories` (`idCategories`),
  CONSTRAINT `fk_Products_Inventory1`
    FOREIGN KEY (`idInventory`)
    REFERENCES `shop`.`inventory` (`idInventory`),
  CONSTRAINT `fk_Products_Suppliers1`
    FOREIGN KEY (`idSuppliers`)
    REFERENCES `shop`.`suppliers` (`idSuppliers`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`detail_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`detail_orders` (
  `idDetail_orders` INT NOT NULL,
  `idOrders` INT NOT NULL,
  `idProducts` INT NOT NULL,
  PRIMARY KEY (`idDetail_orders`),
  INDEX `fk_Detail_orders_Orders1_idx` (`idOrders` ASC) VISIBLE,
  INDEX `fk_Detail_orders_Products1_idx` (`idProducts` ASC) VISIBLE,
  CONSTRAINT `fk_Detail_orders_Orders1`
    FOREIGN KEY (`idOrders`)
    REFERENCES `shop`.`orders` (`idOrders`),
  CONSTRAINT `fk_Detail_orders_Products1`
    FOREIGN KEY (`idProducts`)
    REFERENCES `shop`.`products` (`idProducts`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shop`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`payments` (
  `id_payments` INT NOT NULL,
  `idOrders` INT NOT NULL,
  `amount_payments` VARCHAR(45) NOT NULL,
  `date_payments` DATE NOT NULL,
  PRIMARY KEY (`id_payments`),
  INDEX `fk_Payments_Orders1_idx` (`idOrders` ASC) VISIBLE,
  CONSTRAINT `fk_Payments_Orders1`
    FOREIGN KEY (`idOrders`)
    REFERENCES `shop`.`orders` (`idOrders`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
>>>>>>> f7b17f7 (XML and JAXB added)
